### PR TITLE
Custom local executor

### PR DESCRIPTION
**Pull request by gungorbudak**
This PR adds ability to set a custom local executor to Composer and provides live logging feature to track execution logs in real time on the Composer interface.

### CODE REVIEW

**Comment by kaushik-work** [comment]
@gungorbudak there is a request from @marijanlekic if you could please squash the commits in this PR. His code review is basically done, and he sees no issues, however, it would be neater if the commits for this feature could be squashed together. Thanks!

**Comment by kaushik-work** [comment]
Hi @gungorbudak 

We had a discussion about this great PR and the general question of enabling different CWL executors. We decided that for a good user experience we will continue to bundle Rabix Executor but want to ensure that only `sbg:draft2` tools/workflows invoke this. CWL 1.x tools/workflows will invoke the executor indicated by your addition, and not Rabix Executor.

To this end, could you modify your PR as follows

1. In the screen for adding a custom executor, could you add a label box that states:
```
Legacy `sbg:draft2` tools and workflows will be executed with the bundled Rabix Executor
CWL 1.x tools and workflows will be executed with the cwl-runner set here. 
```
With a link to for further information to the following text

```
sbg:draft2 and Rabix Executor
=============================

`sbg:draft2` is a legacy version of the CWL specification. The only executor 
that runs this legacy version outside of any Seven Bridges platform is Rabix Executor. 
While Rabix Executor is a fully functional executor sutable for testing `sbg:draft2`
workflows locally, the code is no longer maintained. In addition, Rabix Executor 
does not run properly on Windows. 

For convenience, Rabix Executor is bundled with Rabix Composer and can be used to
test run `sbg:draft2` tools and workflows. It is strongly reccomended that you 
update any still used `sbg:draft2` tools and workflows to at least CWL 1.0. 

The [SB draft2 upgrader tool](https://github.com/sbg/sevenbridges-cwl-draft2-upgrader) 
can help with the updating.
```

2. Could you add logic in the code related to the test pane such that `sbg:draft2` apps invoke Rabix Executor (**but not on windows**) and CWL 1.x apps invoke the executor that is indicated in the settings.


cc: @marijanlekic

**Comment by gungorbudak** [comment]
Hi @kaushik-work I'll work on this modification and update the PR. Thanks

**Comment by gungorbudak** [comment]
@kaushik-work I implemented extra features required to run draft-2 apps and updated the repo with the main repo however I couldn't squash the commits. I'll try once more otherwise GitHub has the feature to squash during merge so we can always use that option.

**Pull request closed without merging**
